# Generated by Django 4.0.3 on 2022-04-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_bookinstance_imprint_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Over'), ('a', 'Available')], default='o', help_text='Book availability', max_length=1),
        ),
    ]
