# Generated by Django 4.0.3 on 2022-04-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(default='Some information about writer', max_length=5000),
        ),
    ]
