# Generated by Django 4.0.3 on 2022-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_author_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(default='Some information about writer', help_text='Enter text about writer', max_length=5000),
        ),
    ]
