# Generated by Django 4.0.3 on 2022-04-12 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_author_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='author_photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(default='Some information about writer', help_text='Enter information about writer', max_length=5000),
        ),
    ]
