# Generated by Django 4.0.3 on 2022-04-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_author_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='photo',
        ),
        migrations.AddField(
            model_name='author',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
