# Generated by Django 4.0.3 on 2022-04-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_author_photo_author_author_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_photo',
            new_name='photo',
        ),
    ]
