# Generated by Django 4.0.3 on 2022-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_author_photo_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='short_biography',
            field=models.CharField(default='Write a little about the author', max_length=550),
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(default='Write more about the author', help_text='Enter information about writer', max_length=10000),
        ),
    ]
