# Generated by Django 4.0.3 on 2022-04-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_author_short_biography_alter_author_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_image'),
        ),
        migrations.AlterField(
            model_name='author',
            name='short_biography',
            field=models.TextField(default='Write a little about the author', max_length=550),
        ),
    ]
