# Generated by Django 4.0.3 on 2022-04-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_book_image_alter_author_short_biography'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
