# Generated by Django 4.0.3 on 2022-04-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_author_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='favorites',
        ),
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(help_text='Choose favorite books', related_name='created', to='catalog.book'),
        ),
    ]
