# Generated by Django 4.0.3 on 2022-04-16 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0020_remove_book_favorites_book_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(default='None', help_text='Choose favorite books', related_name='created', to=settings.AUTH_USER_MODEL),
        ),
    ]
